version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: creative-studio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: creative_studio
      MYSQL_USER: creative_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - creative-studio-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: creative-studio-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - creative-studio-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: creative-studio-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - creative-studio-network
    restart: unless-stopped

  # Creative Studio Server
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: creative-studio-server
    environment:
      - GIN_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=creative_studio
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET=your-production-secret-key
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/root/uploads
    networks:
      - creative-studio-network
    depends_on:
      - mysql
      - redis
      - rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: creative-studio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - creative-studio-network
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  creative-studio-network:
    driver: bridge